[package]
name = "web-server"
version = "0.1.0"
edition = "2021"

[dependencies]
postgres = "0.19.9"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
serde_derive = "1.0.217"
log = "0.4.25"
log4rs = "1.3.0"
